name: base_bloc
description: Base bloc package.
version: 0.0.4
homepage: https://github.com/spiderion/base_bloc

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
